services:
  redis:
    image: redis:7-alpine
    container_name: projectnow-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:16-alpine
    container_name: projectnow-postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pharmahub
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
